-- MySQL dump 10.13  Distrib 5.7.16, for Linux (x86_64)
--
-- Host: mysql.info.unicaen.fr    Database: niveau_dev
-- ------------------------------------------------------
-- Server version	5.5.53-0+deb8u1-log

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `recettes`
--

DROP TABLE IF EXISTS `recettes`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `recettes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) DEFAULT NULL,
  `author_name` varchar(255) DEFAULT NULL,
  `temps` int(11) DEFAULT NULL,
  `ingredients` varchar(255) DEFAULT NULL,
  `preparation` text DEFAULT NULL,
  `image_url` varchar(255) DEFAULT NULL,
  `creation_date` datetime DEFAULT NULL,
  `tag` varchar(255) DEFAULT NULL,
  `avis` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=109 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
--
-- Dumping data for table `animals`
--

LOCK TABLES `recettes` WRITE;
/*!40000 ALTER TABLE `recettes` DISABLE KEYS */;
INSERT INTO `recettes` VALUES (1,'Raclette','Toto','5','1kg patates, Fromage à raclette', 'Faire bouillir les patates dans une casserole d\'eau, chauffer la machine à raclette, ajouter des ingrédients si besoin','https://www.papillesetpupilles.fr/wp-content/uploads/2016/12/Raclette-%C2%A9beats1-shutterstock.jpg','2020-01-30 12:56:17','français, repas','5,4');
INSERT INTO `recettes` VALUES (2,'Gateau au Yaourt','Toto','15','1 pot de yaourt, 4 oeufs, 1 pot de farine, 1 pot de sucre, 1 pot d\'huile', 'Tout melanger, four 180 C','https://assets.afcdn.com/recipe/20130924/34684_w1024h768c1cx2592cy1728.jpg','2020-01-30 13:01:30', 'français, sucré, gateau',NULL);
INSERT INTO `recettes` VALUES (3, 'Côtelettes de mouton, pomme de terre', 'Tante Marie', 8, '4 côtelettes, 50g de beurre, 100g de chapelure, sel, poivre, patates', 'Roulez les côtelettes dans de la chapelure et mettez les sur le gril à feu pas trop vif (ou dans la poêle). Retournez-les, salez et poivrez. Servez avec des pommes de terre risolées au beurre ou avec une purée de pommes de terre', 'https://cuisine-addict.com/wp-content/uploads/2014/01/cote-agneau-moutarde-herbes-1200x500.jpg', '0000-00-00 00:00:00', 'français, plat, viande, chaud',NULL);
INSERT INTO `recettes` VALUES (4, 'Paella', 'Leonardo', 60, '200g de riz, 12 à 14 langoustines cuites au court-bouillon, 1 poulet, 5 à 6 cuillérées de pois cuits, 1 litre de moules, 100g de crevettes, 3 tomates, 1 oignon, 1/2 litre de bouillon, huile d\'olive, sel, poivre', 'Dans ne sauteuse, faites revenir l\'huile,Faites bouillir 1 litre d\'eau avec 1 cuillère à soupe d\'huile d\'olive, les herbes de Provence, sel et poivre.Dès l\'ébullition, versez en pluie 250 g de Polenta Tipiak et remuez quelques minutes jusqu\'à ce qu\'elle épaississe.Etalez la Polenta Tipiak sur 1 cm d\'épaisseur dans un plat légèrement huilé et laissez-la refroidir.Faites revenir les oignons dans 2 cuillères à soupe d\'huile d\'olive, sucre, sel et poivre.Faites cuire 6 tranches d\'aubergines épaisses d\'1 cm dans un filet d\'huile d\'olive et 1 dl d\'eau. Lorsque le liquide s\'est évaporé, salez et poivrez. Laissez dorer. Une fois la polenta refroidie, découpez-y 12 disques à l\'emporte-pièce et faites-les dorer dans un peu d\'huile d\'olive.Placez les tranches d\'aubergines entre deux palets de polenta à la façon « hamburger » et décorez sur le dessus avec les lamelles d\'oignons. Servez avec une salade verte.', 'https://www.tipiak.fr/sites/default/files/styles/image_detail/public/recettes/images/Palets-polenta-facon-hamburger-vegetarien-TIPIAK.jpg?itok=65JM2mJ4', '2020-02-27 07:35:30', 'vegetarien, plat',NULL);
INSERT INTO `recettes` VALUES (5, 'Gateau facile chocolat et coco', 'Marmiton', 100, '40cl de lait concentré sucré, 125 g de noix de coco rapée, 2 oeufs, 40 cl de lait frais, 100 g de chocolat, 10 cl de lait ', 'Mélangez le lait concentré la noix de coco râpée les oeufs et le lait frais, puis versez le tout dans un moule à cake. Recouvrez de papier alu. Faitez cuire au bain-marie à 180°C (thermostat 6) pendant 1h20. Laissez refroidir, puis nappez de chocolat (100 g de chocolat fondus dans du lait). Laissez refroidir au frais pendant au moins une nuit.', 'https://assets.afcdn.com/recipe/20160920/3882_w648h414c1cx3333cy2496.jpg', '2020-05-30 03:43:35', 'dessert, francais, gateau, froid',NULL);
INSERT INTO `recettes` VALUES (6, 'Mont d’or par FAST[OCHE]', 'Fastoche', 60, '1 saucisse de Morteau, 1 gousse d’ail dégermée, 1 fromage Mont d’Or en boîte, 5cl de vin blanc, 8 pommes de terre moyennes, sel', 'ÉTAPE 1 Préchauffer le four à 190°C. ÉTAPE 2 Trancher la saucisse de Morteau et fendez l’ail dégermée en 2. ÉTAPE 3 Faire un trou au centre du Mont d’Or et y insérer l’ail. ÉTAPE 4 Verser ensuite le vin blanc. Remettre le haut du fromage et enfourner pendant 30 minutes. ÉTAPE 5 Faire bouillir les pommes de terre avec la peau dans de l’eau bouillante salée pendant 10 minutes. ÉTAPE 6 Rajouter les tranches de saucisse de Morteau et laisser cuire encore 10 minutes. ÉTAPE 7 Servir le fromage Mont d’Or chaud accompagné de pommes de terre et de saucisse de Morteau.', 'https://static.cuisineaz.com/240x192/i151328-mont-d-or-par-fast-oche.jpeg', '2020-02-22 14:45:30', 'entree, francais, montagne, chaud, hiver',NULL);
INSERT INTO `recettes` VALUES (7, 'Hachis Parmentier au fromage', 'Tipiak', 80, '1 kg de pommes de terre ,1 c. soupe d’huile d’olive,20 cl de lait,800 g de viande de bœuf hachée,2 c. soupe de crème fraîche, 3 c. soupe de sauce bolognaise,70 g d’Emmental râpé, Persi', '. Epluchez les pommes de terre et coupez-les en morceaux. Faites-les cuire 30 min. dans de l’eau bouillante salée, égouttez-les et écrasez-les au presse-purée.Ajoutez le lait, la crème fraîche, 20 g d’Emmental râpé, le Comté et 25 g de beurre, Préchauffez votre four à 180° C,Faites revenir les oignons dans l’huile. Ajoutez le bœuf et laissez dorer 5 minutes, Ajoutez la bolognaise et le persil, assaisonnez.. Beurrez un plat allant au four, versez-y la viande puis la purée.. Saupoudrez du reste d’Emmental râpé mélangé à la Chapelure Dorée Tipiak, Enfournez pour 20 min. Servez aussitôt.', 'https://www.tipiak.fr/sites/default/files/styles/image_detail/public/2019-09/cdore_parmentier_au_fromage_hd.jpg?itok=Ipb92ept', '2020-02-28 08:42:30', 'chaud, francais, viande',NULL);
INSERT INTO `recettes` VALUES (8, 'Palets de Polenta façon hamburger végétarien', 'Tipiak', 30, '250 g de Polenta Tipiak, 6 tranches épaisses d\'aubergines,3 gros oignons coupés en rondelles,1 c. à café herbes de Provence,1 c. soupe d\'huile d\'olive,1/2 c. à soupe de sucre, Sel, poivre', 'Faites bouillir 1 litre d\'eau avec 1 cuillère à soupe d\'huile d\'olive, les herbes de Provence, sel et poivre.Dès l\'ébullition, versez en pluie 250 g de Polenta Tipiak et remuez quelques minutes jusqu\'à ce qu\'elle épaississe.Etalez la Polenta Tipiak sur 1 cm d\'épaisseur dans un plat légèrement huilé et laissez-la refroidir.Faites revenir les oignons dans 2 cuillères à soupe d\'huile d\'olive, sucre, sel et poivre.Faites cuire 6 tranches d\'aubergines épaisses d\'1 cm dans un filet d\'huile d\'olive et 1 dl d\'eau. Lorsque le liquide s\'est évaporé, salez et poivrez. Laissez dorer.Une fois la polenta refroidie, découpez-y 12 disques à l\'emporte-pièce et faites-les dorer dans un peu d\'huile d\'olive.Placez les tranches d\'aubergines entre deux palets de polenta à la façon « hamburger » et décorez sur le dessus avec les lamelles d\'oignons. Servez avec une salade verte.', 'https://www.tipiak.fr/sites/default/files/styles/image_detail/public/recettes/images/Palets-polenta-facon-hamburger-vegetarien-TIPIAK.jpg?itok=65JM2mJ4', '2020-02-27 07:35:30', 'vegetarien, plat',NULL);
INSERT INTO `recettes` VALUES (9, 'Brochettes et légumes à l\'Orientale au Boulgour', 'Tipiak', 8, '200 g de Boulgour Tradition Tipiak400 g de gigot d\'agneau,400 g de bœuf,3 gousses d\'ail,1 c. à café de raz-el-hanout,6 c. à soupe d\'huile d\'olive,1 courgette,1 petit poivron rouge,2 tomates pelées,2 c. à soupe de pois chiches en boîte,', 'Coupez les viandes en cubes et laissez les mariner 1 heure dans un plat avec 2 gousses d\'ail pressées, ½ cuillère à café de raz-el-hanout, 4 cuillères à soupe d\'huile d\'olive et un peu de sel.Pendant ce temps, lavez et coupez la courgette en dés et le poivron en morceaux.Pelez et pressez la gousse d\'ail restante.Faites revenir la courgette, le poivron et l\'ail avec le reste d\'huile d\'olive. Ajoutez le reste de raz-el-hanout et 2 cuillères à soupe d\'eau. Couvrez et laissez cuire 10 minutes à feu moyen.Coupez les tomates en morceaux et ajoutez-les à la ratatouille.Ajoutez les pois chiches. Salez, poivrez et cuire 5 minutes à couvert.Préparez le Boulgour Tradition Tipiak comme indiqué sur la boîte.Pendant ce temps, embrochez les cubes de viande avec les tomates cerises et les lamelles d\'oignon coupé en 8.Saupoudrez de sésame grillé et faites les griller au four pendant 15 minutes à 210°C (th.7).Servez les brochettes avec les légumes et le Boulgour Tradition Tipiak.', 'https://www.tipiak.fr/sites/default/files/styles/image_detail/public/recettes/images/Brochettes-legumes-orientale-boulgour-TIPIAK.jpg?itok=M1WhwgrU', '2020-02-26 06:35:30', 'oriental, plat',NULL);
INSERT INTO `recettes` VALUES (10, 'Quinoa à la noix de coco et crevettes au curry', 'Tipiak', 50, '2 c. à soupe d\'huile d\'olive,2 oignons moyens,3 gousses d\'ail,2 c. à soupe de curry en poudre,1 c. à café de cumin moulu,2 c. à soupe de sauce soja,2 à 3 carottes en rondelles,500 g de crevettes cuites décortiquées,240 g de petits pois sur', 'Dans une poêle, versez l\'huile d\'olive et faites suer les oignons émincés ; ajoutez l\'ail haché.Saupoudrez de curry et de cumin puis ajoutez la sauce soja et les carottes. Versez 3,5 verres d\'eau et assaisonnez. Portez à ébullition puis laissez mijoter à feu doux avec un couvercle pendant 10 minutes.Incorporez les crevettes, les petits pois et prolongez la cuisson toujours à couvert pendant 5 minutes.Pendant ce temps, dans une casserole, mélangez le lait de coco et 1,5 l d\'eau salée puis portez à ébullition. Plongez les sachets cuisson de Quinoa Blanc Sélection Tipiak, couvrez et laissez cuire 15 minutes à constante ébullition.Sortez les sachets à l\'aide d\'une fourchette et laissez égoutter 30 secondes. Ouvrez les sachets en tirant sur la partie prédécoupée. Versez le Quinoa Blanc Sélection Tipiak dans un plat.Faites dorer à la poêle la noix de coco râpée, ajoutez au Quinoa Blanc Sélection Tipiak cuit.Servez bien chaud avec les crevettes.', 'https://www.tipiak.fr/sites/default/files/styles/image_detail/public/2017-09/quinoa-noix-coco-crevettes-curry-tipiak.jpg?itok=aDCz10yT', '2020-02-25 02:35:30', 'plat',NULL);
INSERT INTO `recettes` VALUES (11, 'Cheese-cake et son coulis perlé de framboises', 'Tipiak', 40, '10 biscuits type spéculoos,40 g de beurre fondu, 600 g de coulis de framboises surgelé,250 cl d\'eau,100 g de Perles Japon potages et desserts Tipiak, 4 feuilles de gélatine,20 cl de crème liquide,300 g de mascarpone,80 g de sucre en poudre,2', 'Réduisez les biscuits en poudre fine et incorporez le beurre du bout des doigts. Placez cette préparation dans le fond d\'une terrine beurrée, bien tasser et placez au frais.Placez les feuilles de gélatines dans un bol d\'eau froide pendant 10 minutes.Faites bouillir le coulis et l\'eau. Ajoutez les Perles Japon potages et desserts Tipiak et laissez cuire 15 minutes à feu doux en remuant régulièrement.Faites chauffer légèrement la crème liquide et incorporez les feuilles de gélatine bien essorées.Fouettez le mascarpone avec le sucre en poudre et l\'extrait de vanille. Puis incorporez le mélange à la crème liquide avec gélatine.Versez le tiers du coulis perlé sur la base biscuitée puis la moitié de l\'appareil mascarpone.Déposez ensuite un autre tiers du coulis et terminez par le reste de mélange à base de mascarpone.Laissez refroidir et placez au frais pendant 12 heures.Démoulez et servez en tranches avec le reste du coulis perlé aux framboises.', 'https://www.tipiak.fr/sites/default/files/styles/image_detail/public/recettes/images/Cheese-cake-coulis-perle-framboises-TIPIAK.jpg?itok=VsChb9bY', '2020-02-22 14:35:30', 'dessert',NULL);
INSERT INTO `recettes` VALUES (12, 'pâte pour empanadas', 'laylita', 8, '360 g de farine tout usage,¼ c. à café sel,170 g de beurre non-salé (1 ½ bâtonnets),1 œuf,100 ml d’eau ou lait (entre 100ml et 120ml, ajuster)', 'Préparation de la pâte à empanadas maison:Mélanger la farine et le sel dans un robot de cuisine.Ajouter le beurre.Ajouter l\'œuf et l\'eau/lait jusqu\'à obtention d\'une pâte grumeleusePour faire la pâte à empanadas à la main, suivre les mêmes instructions, mais mélanger les ingrédients ensemble avec les mains.Former une boule, l\'aplatir légèrement.Étaler la pâte en une fine couche et découper des formes de disques ronds à empanadas (utiliser des moules ronds ou une petite assiette).Utiliser immédiatement ou conserver au réfrigérateur / congélateur pour une utilisation ultérieure.Assemblage et cuisson des empanadas :Pour assembler les empanadas ou chaussons, placer une cuillerée de farce sur le milieu de chaque disque à empanada. La quantité de garniture varie en fonction de la taille de l\'empanada, mais en général, il est plus facile de refermer un empanada qui n\'est trop garni. Aussi, plus vous faites d’empanadas, plus il vous sera facile de les garnir au maximum tout en les refermant correctement.Pour refermer les empanadas, plier le disque et souder les bords en appuyant sur la pâte avec vos doigts. S’il vous est difficile de souder les bords, vous pouvez badigeonner l\'intérieur des bords à l\'’\'aide d\'’\'un pinceau avec du blanc d\'œuf, il agira comme colle pour les empanadas. Vous pouvez également utiliser une fourchette pour souder les bords, appuyez simplement avec le haut de la fourchette sur les bords. Pour la repulgue ou churito, le joint de type boucle, utilisez vos doigts pour tourner la boucle sur les bords. Il existe aussi des moules à empanada que vous pouvez acheter qui vous aideront à souder les empanadas.Pour de meilleurs résultats, je recommande de mettre les empanadas au réfrigérateur pendant au moins 30 minutes avant de les cuire - cela leur permettra de mieux se refermer et empêchera la garniture de s\'échapper.Si vous voulez que vos empanadas aient un bel aspect doré, alors vous pouvez les badigeonner d’œuf (un œuf entier battu ou bien juste un jaune d\'œuf et quelques gouttes d\'eau battus ensemble).Cuire les empanadas dans un four préchauffé. Je les fais cuire généralement à 190-200°C, la température varie en fonction du four et de la taille des empanadas. Je cuis les empanadas de plus petite taille à 190°C. Le temps de cuisson varie également (encore une fois en fonction du four et la taille), entre 18 et 25 minutes - les empanadas sont prêts une fois qu’ils sont dorés.', 'https://www.laylita.com/recettes/wp-content/uploads/2014/07/Pr%C3%A9paration-pate-empanada-640x513.jpg', '2020-02-22 15:25:30', 'végétarien, plat',NULL);
INSERT INTO `recettes` VALUES (13, 'Ceviche d’huîtres', 'Laylita', 30, '6 grosses huitres,¼ d’oignon rouge finement haché ou tranché,1 tomate finement hachée Suggestion: enlever les pépins,½ poivron vert finement haché et débarrassé des graines et des segments blancs,½ C.a.c de coriandre hachée très finement,5 citro', 'Faire tremper les tranches d’oignons dans une tasse d’eau froide avec 1 C.a.c de sel, rincer et bien égoutter. Mariner avec le jus de 1 citron vert.Ouvrir les huîtres.Retirer la chair des huîtres tout en gardant leur eau et découper en petit dés.Dans un bol moyen mélanger les huitres, les morceaux de tomates et poivrons verts, le jus de citron vert, la coriandre hachée, l’huile et le sel selon votre goût.Laisser mariner pendant 5 à 10 minutes et servir immédiatement.', 'https://www.laylita.com/recettes/wp-content/uploads/2018/02/Ceviche-huitres-768x512.jpg', '2020-02-20 16:15:30', 'poisson, plat',NULL);
INSERT INTO `recettes` VALUES (14, 'Soupe de quinoa et fromage', 'laylita', 30, '2 c.à.s d’huile2 tasses d’oignon émincé à peu prés un gros oignon4 gousses d’ail écrasées1 tomate émondée sans graine et hachée finement1 c.à.c de cumin1 c.à.c c.à.c de roucou1 c.à.c c.à.c d’origan séché6 pommes de terre pelées et coupées en', 'Chauffer l’huile à feu moyen dans une grande marmite.Ajouter l’oignon, l’ail la tomate le cumin, le roucou, l’origan et le sel et le poivre. Bien mélanger et cuire jusqu’à ce que les oignons ramollissent, soit 5 à 8 minutes.Ajouter les pommes de terre, bien remuer pour les couvrir d’oignon et d’épices, continuer la cuisson encore 5 minutes en remuant de temps en temps.Ajouter l’eau ou le bouillon et porter à ébullition.Ajouter le quinoa, réduire le feu et mijoter jusqu’à ce que le quinoa et la pomme de terre soient cuits, soit, à peu prés 25 minutes. Remuer de temps en temps. Pour une consistance plus crémeuse et épaisse vous pouvez utiliser un presse purée ou une cuillère en bois pour écraser quelques un des morceaux de pommes de terre.Ajouter le lait et le fromage, remuer et laisser cuire encore 5 minutes.Retirer du feu. Ajouter la coriandre ou le persil haché, gouter et rectifier en sel et poivre selon votre goût.Servir la soupe avec des tranches ou des dés d’avocats et de la sauce piquante selon votre envie.', 'https://www.laylita.com/recettes/wp-content/uploads/2018/02/soupe-de-quinoa-et-fromage-avec-patates-et-avocat.jpg', '2020-02-10 16:25:30', 'soupe, vegetarien',NULL);
INSERT INTO `recettes` VALUES (15, 'Polpette di riso arancini', 'regal', 150, '300 g Riz à risotto Arborio ou Carnaroli,1 Oignon,2 c. à soupe Huile d\'olive,75 cl Bouillon de volaille,10 cl Vin blanc sec,60 g Parmesan,2 c. à soupe Mascarpone,2 boules Mozzarella,3 brins Thym,2 Oeuf,100 g Farine,100 g Chapelure,', '1 Dans une casserole, faites chauffer le bouillon. Pelez et ciselez l’oignon. Faites-le revenir dans une sauteuse avec l’huile, sans le laisser colorer.2 Ajoutez le riz et mélangez jusqu\'à ce qu\'il s’enrobe de matière grasse. Versez le vin blanc et laissez complètement évaporer.3 Versez ensuite le bouillon, louche après louche. Salez, poivrez, laissez cuire pendant 18 min en mélangeant régulièrement.4 Hors du feu, ajoutez le parmesan, le thym effeuillé et le mascarpone. Mélangez et laissez refroidir.5 Coupez la mozzarella en dés. Formez des boules de riz avec les mains humides. Enfoncez un doigt au centre de chaque boule, puis glissez un morceau de mozzarella à l’intérieur. Refermez le trou avec un peu de riz et remodelez les boules.6 Préparez 3 assiettes creuses avec la farine dans la première, les oeufs battus dans le deuxième et la chapelure dans la troisième. Passez les boules successivement dans les trois assiettes. Disposez-les au fur et à mesure sur un plat.7 Chauffez l’huile de friture et faites dorer les croquettes par petites quantités, en les retournant à l’aide d’une écumoire.8 Transvasez-les sur une assiette recouverte de papier absorbant. Servez aussitôt.', 'https://i-reg.unimedias.fr/sites/art-de-vivre/files/styles/recipe/public/Import/PhotoCuisine_60348599.jpg?auto=compress%2Cformat&crop=faces%2Cedges&cs=srgb&fit=crop&h=500&w=393', '2020-02-22 17:25:30', 'italien, entree',NULL);
INSERT INTO `recettes` VALUES (16, 'ORÉO SANS GLUTEN', 'Lucie Dugua', 8, '190 g de farine de riz Ma Vie Sans Gluten,150 g de sucre blond de canne + 125 g de sucre glace,60 g de cacao en poudre (non sucré),1 œuf,250 g de margarine ramollie ou d’huile de coco (150 g pour les biscuits, 100 g pour la crème),2 cuillère', 'PRÉPARATION DE LA PÂTE À BISCUITFouetter 150 g de margarine texture pommade avec 150 g de sucre blond jusqu’à ce que le mélange devienne légèrement mousseux. Incorporer l’œuf et les graines contenues dans la moitié de la gousse de vanille. Placer dans un saladier la farine de riz, la poudre à lever, le cacao. Mélanger et y incorporer la préparation précédente jusqu’à obtenir une pâte homogène. L’envelopper dans un film étirable pour la réserver 1 heure au réfrigérateur.CONFECTION ET CUISSON DES BISCUITS AU CACAOSur un plan de travail fariné ou directement sur un tapis de cuisson, étaler la pâte au rouleau sur 3 mm d’épaisseur environ. A l’aide d’un petit emporte-pièce, tailler des morceaux de forme ronde et les placer sur une plaque munie d’un papier sulfurisé. Recommencer le processus ainsi avec les restes de pâte. Enfourner pour 10 à 12 minutes de cuisson au four à 180°C. Laisser refroidir quelques minutes à la sortie du four puis déplacer les biscuits sur une grille.RÉALISATION DE LA CRÈME VANILLÉE ET MONTAGE DES ORÉO SANS GLUTENFouetter 100 g de matière grasse légèrement ramollie avec le sucre glace et la vanille. Garnir la moitié des biscuits avec la crème vanillée. Refermer avec l’autre moitié en pressant pour répartir la garniture.', 'https://www.maviesansgluten.bio/wp-content/uploads/2020/03/recette_oreo_sans_gluten.jpg', '2020-03-31 20:25:30', 'sans gluten, vegetarien',NULL);
INSERT INTO `recettes` VALUES (17, 'Fondant au chocolat sans gluten sans lactose', 'papilleetpupille', 35, '200 g de chocolat noir (lisez la composition pour bien voir qu’il n’y a ni gluten, ni lactose. Des fois ils mettent des trucs bizarres dans le chocolat)3 œufs bio90 g de sucre de canne non raffiné (muscovado, rapadura )20 cl de de lait de coco ou de', 'Préchauffez le four à 180°C, chaleur tournante.Faites fondre le chocolat au bain-marie ou au micro-onde. Séparez le blanc des jaunes. Mettez les jaunes et le sucre dans un saladier et fouettez jusqu’à ce que le mélange blanchisse. Incorporez ensuite le chocolat fondu, le lait de coco et la vanille.  Mélangez puis ajoutez la Maïzena et la poudre d’amandes.Battez les blancs en neige ferme et incorporez-les délicatement au mélange à base de chocolat.Versez dans un moule à gâteau et enfournez pour 15 à 20 minutes de cuisson. Pour être sûr de la bonne cuisson, enfoncez la lame d’un couteau au coeur du gâteau, elle doit ressortir sèche.Enjoy !', 'https://www.papillesetpupilles.fr/wp-content/uploads/2017/01/Fondant-au-chocolat-sans-lait-sans-gluten-c-gorka-arcocha-CC-BY-NC-ND-2.0-750x0.jpg', '2020-03-30 21:45:30', 'dessert, sans lactose',NULL);
INSERT INTO `recettes` VALUES (18, 'Velouté de potiron au massalé', 'papilleetpupille', 45, '750 g de potiron,1 cuillère à soupe d’huile d’olive,1 oignon,1 cuillère à soupe de massalé malbar (clic pour le découvrir),300 ml d’eau (ou de bouillon de légumes ou de volaille pour les non végétariens),1 pincée de sel', 'Pelez le potiron, lavez-le et coupez-le en dés. Epluchez l’oignon et ciselez-le. Mettez l’huile d’olive dans une cocotte. Quand elle est chaude, ajoutez les oignons ciselés et faites les revenir environ 5 minutes. Ajoutez le massalé, les dés de potiron et mouillez à peine à hauteur avec l’eau.  Couvrez et laissez cuire 30 minutes à feu doux.Mixez, goûtez, rectifiez l’assaisonnement et servez. Si vous êtes très gourmand n’hésitez pas à ajouter une cuillère à soupe de crème fraîche épaisse. J’en ai acheté une au marché qui est succulente (crème crue et bio, miam). Et si vous êtes intolérant au lactose, une cuillère à soupe de crème de coco, c’est super bon aussi.Bon app’', 'https://www.papillesetpupilles.fr/wp-content/uploads/2019/12/Veloute%CC%81-de-potiron-au-massale%CC%81-1150x0.jpg', '2020-06-30 19:35:30', 'soupe, veloute, sans lactose, végétarien, entrée',NULL);
INSERT INTO `recettes` VALUES (19, 'Pintade aux pommes en cocotte', 'papilleetpupille', 140, '1 belle pintade,4 cuillères à soupe de Verjus (ou 3 cuillères à soupe de jus de pomme + 1 cuillère à soupe de vinaigre de cidre),2 cuillères à soupe d’huile d’olive,1 cuillère à café d’aiguilles de romarin,1 cuillère à café de feuilles de thym,\r', 'Dans un bol, mettez le sel, le piment, le thym, le romarin, l’huile d’olive et 2 cuillères à soupe de verjus. Mélangez.  Mettez la pintade dans une cocotte et frottez-la avec ce mélange, sur toutes les faces. Versez ce qu’il reste de cette préparation dans la cocotte. Ajoutez 2 échalotes pelées et coupées en 4 et 3 gousses d’ail pelées.Fermez le couvercle de la cocotte et enfournez à froid pour 1 heure de cuisson – Température 210°C, chaleur tournante (je me sers de la fonction Circosteam de mon four vapeur).Au bout d’une heure, sortez la pintade du four et ajoutez les pommes pelées, épépinées et coupées en lamelles grossières. Ajoutez 2 cuillères à soupe de verjus, couvrez à nouveau et ré-enfournez pour 20 minutes, toujours à 210°C.Les pommes sont ainsi confites dans le jus, c’est trop trop trop bon !', 'https://www.papillesetpupilles.fr/wp-content/uploads/2019/04/Pintade-aux-pommes-Chantecler-1150x0.jpeg', '2020-07-07 18:55:30', 'sans lactose, sans oeufs, plat, viande',NULL);
INSERT INTO `recettes` VALUES (20, 'Smashed potatoes : Les pommes de terre écrasées', 'papilleetpupille', 60, '1 kg de pommes de terre (j’avais des rattes du Touquet)5 gousses d’ail5 cuillères à soupe d’huile d’olive1 bonne pincée de sel1 cuillère à soupe de thym1 cuillère à soupe de persil plat.', 'Lavez les rattes, ne les pelez pas, ce n’est pas la peine.  Portez à ébullition une casserole d’eau salée et plongez-les pour 15 à 20 minutes de cuisson. J’avais coupé les plus grosses en deux. Pour s’assurer qu’elles sont bien cuites, plongez en leur coeur la lame d’un couteau, elle doit pénétrer sans problème. Au bout de 10 minutes de cuisson des pommes de terre, ajoutez les gousses d’ail non pelées.Egouttez les pommes de terre et l’ail, laissez-les reposer 5 minutes puis déposez-les sur une plaque de cuisson anti adhésive ou recouverte de papier sulfurisé. Ajoutez les gousses d’ail dont vous aurez ôté la peau.A l’aide d’un verre, d’une fourchette, d’un zigouigoui à purée écrasez grossièrement les pommes de terre et l’ail.Arrosez le tout d’huile d’olive et saupoudrez de thym.Enfournez dans un four préchauffé à 220°C pour 30 à 35 minutes de cuisson. Les pommes de terre sont ainsi à la fois croustillantes  (grillées) et fondantes. Trop bien.Saupoudrez de sel et si vous le souhaitez d’un peu de persil plat ciselé après cuisson.', 'https://www.papillesetpupilles.fr/wp-content/uploads/2019/12/Smashed-potaoes-1150x0.jpg', '2020-02-08 17:45:30', 'plat, sans oeufs',NULL);
INSERT INTO `recettes` VALUES (21, 'Crumble express à l’abricot', 'papilleetpupille', 30, '1 kg d’abricots bien mûrs,100 g de sucre roux,1 bâton de vanille,3 cuillères à soupe d’eau,250 g de sablés type sablés bretons', 'Mixez les biscuits de façon à obtenir des miettes grossières.Lavez les abricots, fendez-les en deux et dénoyautez-les. Mettez les dans une sauteuses Fendez la gousse de vanille en deux, récupérez les grains et ajoutez-les aux abricots. Ajoutez également l’eau et le sucre. Faites cuire à feu moyen pendant une vingtaine de minutes, jusqu’à ce que les abricots compotent en mélangeant régulièrement.Versez cette compote dans un plat allant au four, recouvrez avec les miettes de biscuits et enfournez dans un four préchauffé, option grill. Faites cuire une petite dizaine de minutes le temps que les miettes dorent.Servez tiède ou froid.', 'https://www.papillesetpupilles.fr/wp-content/uploads/2015/07/Crumble-a-l-abricot-600x523.jpg', '2020-06-07 16:35:30', 'dessert',NULL);
INSERT INTO `recettes` VALUES (22, 'Smoothie framboises myrtilles mangues', 'papilleetpupille', 8, '1 mangue,200 g de myrtilles,125 g de framboises (une barquette),100 ml d’eau,2 glaçons', 'Epluchez la mangue, coupez sa chair en dés. Lavez les myrtilles et les framboises délicatement. Mettez tout dans le bol du blender. Ajoutez 100 ml d’eau et 2 glaçons et mixez.Répartissez la préparation entre 4 verres et servez immédiatement.', 'https://www.papillesetpupilles.fr/wp-content/uploads/2016/01/Smoothie-myrtilles-framboises-mangues-600x778.jpg', '2020-10-12 15:55:30', 'boisson, sans alcool',NULL);
INSERT INTO `recettes` VALUES (23, 'Lait de poule vegan', 'papilleetpupille', 8, '150 g de noix de cajou écrasées,250 ml de lait de coco,8 dattes Deglet Nour,1 cuillère à café de cannelle,1⁄2 cuillère à café d’anis en poudre,20 g de sucre de coco bio,1⁄2 cuillère à café de poudre de vanille bourbon,200 ml d’ea', 'Placez tous les ingrédients dans le bol du blender et mixez jusqu’à obtenir une consistance homogène. Servez le lait de poule glacé avec un bâton de cannelle et un peu vanille en poudre.', 'https://www.papillesetpupilles.fr/wp-content/uploads/2019/09/Lait-de-poule-vegan-1150x0.jpg', '2020-09-30 14:15:30', 'vegan, végétarien, boisson, sans alcool',NULL);
INSERT INTO `recettes` VALUES (24, 'Chaï Latte', 'papilleetpupille', 8, '3 sachet de thé noir de votre choix500 ml de lait entier (ou moitié lait moitié lait de coco, cela fonctionne bien aussi)500 ml d’eau1 bâton de cannelle4 clous de girofle8 gousses de cardamome verte6 grains de poivre2 étoiles de badiane1/2', 'Versez dans une casserole l’eau, les épices, le lait et le sucre dans une casserole. Portez à la limite de l’ébullition puis réduisez le feu et ajoutez les sachets de thé. Laissez infuser le thé (suivez les recommandations du sachet). Comptez environ 3 minutes en remuant de temps en temps.Filtrez à travers une passoire grille fine et servez. C’est super bon !Une version encore plus tip top, c’est de faire chauffer le lait à part, de le faire mousser avec un pied de mixeur ou un Aeroccino (mousseur à lait). Une fois que vous avez une belle mousse, mélangez le lait mousseux et le thé épicé. Trop trop trop trop bon !', 'https://www.papillesetpupilles.fr/wp-content/uploads/2019/12/Chai-latte--1150x0.jpg', '2020-09-29 16:55:30', 'boisson, sans alcool',NULL);
INSERT INTO `recettes` VALUES (25, 'Grog', 'papilleetpupille', 8, '200 ml d’eau,50 ml de rhum ambré,1/2 citron bio (son jus),1 cuillère à café de miel de votre choix (A noter que les miels d’eucalyptus, de thym, de  sapin, sont excellents pour les maux de gorge et les soucis de voies respiratoires),A ceci, vous', 'Versez l’eau dans une casserole. Portez à ébullition, ajoutez le miel, le jus de citron et un zeste prélevée avec un économe, l’épice souhaité et enfin le rhum. Mélangez le temps que le miel fonde et servez bien chaud.', 'https://www.papillesetpupilles.fr/wp-content/uploads/2019/07/Grog-%C2%A9Micaela-Fiorellini-shutterstock-1150x0.jpg', '2020-05-28 17:25:30', 'boisson, avec alcool',NULL);
INSERT INTO `recettes` VALUES (26, 'Virgin sangria aux fruits d’été', 'papilleetpupille', 8, '1 melon,1/2 pastèque,10 grappes de groseilles,1 bouquet de menthe,1 citron,2 cuillères à soupe de sirop d’agave,1 bouteille d’eau plate ou pétillante en fonction de vos goûts.', 'Lavez la menthe. Pressez le jus de citron. Ajoutez lui le sirop d’agave et mettez le tout dans la bouteille. Fendez en deux la melon, ôtez les graines et récupérer la chair à l’aide d’une cuillère parisienne. Coupez la pastèque en deux et récupérez les billes d’une moitié. Gardez l’autre moitié pour une autre recette.Mettez dans la bouteille les billes de melon, de pastèque, les feuilles de menthe et les framboises. La bouteille doit être pleine. Il ne vous reste plus qu’à compléter avec de l’eau pétillante ou plate selon vos goûts.Réservez au réfrigérateur et servez bien frais.Super bon !Variante : A la place de la menthe vous pouvez utiliser des feuilles de basilic.Enjoy ! Sans modération.', 'https://www.papillesetpupilles.fr/wp-content/uploads/2017/06/Boisson-melon-paste%CC%80que-groseille-%C2%A9AnneLataillade-2017-pour-blog-1150x0.jpg', '2020-04-25 19:15:30', 'boisson, sans alcool',NULL);
INSERT INTO `recettes` VALUES (27, 'Pâte à pizza épaisse et moelleuse', 'papilleetpupille', 130, '225 g de farine de blé T55 (Cliquez ici pour découvrir ce qu’est la T55 ? )125 ml d’eau tiède (pas chaude)30 ml d’huile d’olive vierge extra1 cuillère à café de sel2/3 d’un sachet de levure de boulanger déshydratée (environ 7 g)1 cuillère à soup', 'Mettez tous les ingrédients dans le bol du robot ou dans la machine à main et pétrissez jusqu’à obtenir une pâte souple et élastique. Vous pouvez aussi pétrir à la pain jusqu’à obtenir toujours la même consistance.Une fois le pâton formé, mettez-le dans un saladier, couvre-le d’un chiffon et laissez lever environ 1h30 à température ambiante. S’il fait chaud, le pâton lève plus vite, s’il fait froid plus lentement. Il faut qu’il double de volume (environ, on ne fait pas des mathématiques).Au bout de ce laps de temps, renversez le pâton sur le plan de travail légèrement fariné (je le recouvre d’un papier sulfurisé pour pouvoir déplacer ma pâte ensuite plus facilement). Expulsez l’air du pâton et aplatissez la pâte, soit à la main, soit à l’aide d’un rouleau à pâtisserie mais laissez bien les bords un peu plus épais.Déposez cette pâte délicatement sur une plaque allant au four. Laissez lever 15 minutes, toujours dans un endroit tempéré puis garnissez-la.Pour une pizza Margherita d’environ 30 cm de diamètre: Mettez 3 cuillères à soupe de sauce tomate au centre de la pâte et étalez la jusqu’à environ 1 cm des petits boudins qui forment le rebord de la pâte. Arrosez d’une cuillère à soupe d’huile d’olive. Répartissez ensuite 75 g de mozzarella sur la tomate et saupoudrez de quelques feuilles de basilic ciselées.Enfournez pour 8/9 mn de cuisson dans un four préchauffé à 230°C, chaleur tournante. Il faut que le fromage bouillonne. A la sortie du four, mettez à nouveau quelques feuilles de basilic fraîches.Régalez-vous !', 'https://www.papillesetpupilles.fr/wp-content/uploads/2018/05/Pizza-Margherita.%C2%A9stu_spivack-CC-BY-SA-2.0-1150x0.jpg', '2020-12-20 12:32:30', 'pizza',NULL);
INSERT INTO `recettes` VALUES (28, 'Houmous épicé', 'papilleetpupille', 1500, '600 g de pois chiches secs,2,5 cuillères à café de bicarbonate,2 grosses gousses d’ail finement hachées,80 ml de tahini (purée de sésame, dans les magasins bio ou orientaux),2 cuillères à soupe de jus de citron fraîchement pressé,2 cuill', 'Dans un saladier, verser les pois chiches et 1,5 cuillère à café de bicarbonate. Recouvrir le mélange d’eau froide et laisser tremper toute la nuit. Égouttez les pois chiches et versez-les dans une grande casserole d’eau. Ajoutez la cuillère à café restante de bicarbonate et portez à ébullition. Laissez bouillir jusqu’à ce que les pois chiches soient tendres, soit 45 à 50 minutes. Retirer les éventuelles peaux flottant à la surface.Égouttez en conservant 240 ml d’eau de cuisson et laissez les pois chiches refroidir complètement.Dans un robot, versez les pois chiches, l’ail, 240 ml d’eau de cuisson (Si on oublie de conserver de l’eau de cuisson, on peut la remplacer par 240 ml d’eau glacée. Toutefois, l’eau de cuisson donnera davantage de goût au houmous.), le tahini, le jus de citron, la sauce TABASCO® Rouge, 3 cuillères à soupe d’huile d’olive, le sel, le cumin et le poivre, puis mixez jusqu’à obtention d’une préparation lisse et crémeuse.C’est prêt. Il est possible de conserver le houmous dans un récipient hermétique jusqu’à 3 jours.Au moment de dresser, déposez le houmous dans une assiette ou un bol, puis creusez un puits au milieu à l’aide d’une cuillère, avant d’y verser une cuillère d’harissa maison et un filet d’huile d’olive.', 'https://www.papillesetpupilles.fr/wp-content/uploads/2018/09/Houmous-e%CC%81pice%CC%81--1150x0.jpg', '2020-12-25 10:40:30', 'apero, sauce',NULL);
INSERT INTO `recettes` VALUES (29, 'Salade de fruit', 'toto', 5, 'Pomme, fraise, banane, poire', 'Tout couper, mélanger et les lettres au frais ', '', '2020-03-06 20:08:23', 'dessert',NULL);
INSERT INTO `recettes` VALUES (30, 'Chocolat chaud', 'jojo', 5, '100mL de lait, chocolat en poudre, marshmallows, cannelle en poudre', 'Chauffer le lait pendant 40sec au micro-onde, ajouter le chocolat en poudre, bien mélanger, soupoudrer la cannelle, ajouter les marshmallow ', '', '2020-03-06 20:12:50', 'dessert',NULL);
INSERT INTO `recettes` VALUES (31, 'Salade', 'tat', 5, 'salade, vinaigre balsamique', 'laver la salade, tout mélanger', '', '2020-03-07 14:48:19', 'végétarien',NULL);
/*!40000 ALTER TABLE `recettes` ENABLE KEYS */;
UNLOCK TABLES;
